publications = []
# name = "hehe"
# desc = "hehe"
# tags = ["", ""]
# links = [
#   { name = "hello", url = "" },
#   { name = "", url = "" },
# ]

# [[publications]]
# name = "hehe"
# desc = "hehe"
# tags = ["", ""]
# links = [
#   { name = "", url = "" },
#   { name = "", url = "" },
# ]
